### ISSUE TITLE
Instabug overrides default RxJava error handler

### ISSUE THREAD

**Issue by linean** [Instabug/Instabug-Android#126]
Instabug automatically overrides RxJava error handler by calling `RxJavaPlugins.setErrorHandler()` in initialization. Because of that OnErrorNotImplementedException is not throwed anymore and there are no logs in console.

### Steps to Reproduce the Problem
Run this code anywhere in the app:
`        Completable.fromAction(()-> {
            throw new RuntimeException();
        }).subscribe();
`

### Expected Behavior
App should throw:
> io.reactivex.exceptions.OnErrorNotImplementedException

### Actual Behavior
Nothing happens - no logs in console

### Instabug integration code
`
        Instabug.Builder(application, "my_token")
                .setInvocationEvents(InstabugInvocationEvent.TWO_FINGER_SWIPE_LEFT, InstabugInvocationEvent.SHAKE)
                .setReproStepsState(State.ENABLED)
                .setViewHierarchyState(Feature.State.ENABLED)
                .build()
`

### SDK Version
8.0.7

### Android Version
Any

### Device Model
Any

**Comment by Korazy** [comment]
Hey @linean 

Thanks for reaching out. We will look into this and get back to you as soon as possible.

**Comment by jdamcd** [comment]
I'm also seeing this in 8.0.9. The Instabug error handler set on `RxJavaPlugins` is not forwarding exceptions to the thread's uncaught exception handler, so exceptions thrown in e.g. `onSuccess()` callbacks are swallowed silently when they should terminate the app.

**Comment by Korazy** [comment]
Hey all,

Can you try to add a `CompletableObserver()` for the subscription you made and you should be getting the error in `onError` callback, like this:

   ```
Completable.fromAction(new Action() {
            @Override
            public void run() throws Exception {
                throw new IllegalAccessException("Throwable String");
            }

        }).subscribe(new CompletableObserver() {
            @Override
            public void onSubscribe(Disposable d) { }

            @Override
            public void onComplete() { }

            @Override
            public void onError(Throwable e) {
                 // Get the throwable here 
            }
        });
```

**Comment by linean** [comment]
@Korazy it works like this. But this is expected, because observer handles error by itself, and `RxJavaPlugins.onError` is not called.

**Comment by jdamcd** [comment]
As a workaround, it's possible to clear the error handler after initialising Instabug: `  RxJavaPlugins.setErrorHandler(null)`. Surprised to see this being set, especially since we're not using the crash reporting feature.

**Comment by linean** [comment]
And even better is to first get current handler :) 
> val defaultErrorHandler = RxJavaPlugins.getErrorHandler()
> initializeInstabug()
> RxJavaPlugins.setErrorHandler(defaultErrorHandler)

**Comment by Korazy** [comment]
We currently have a fix that's pending review and testing at the moment. I will make sure to update you soon :)

**Comment by jdamcd** [comment]
Hi @Korazy. We've noticed a related issue. The Instabug SDK (8.0.9) is setting a default exception handler, even though we're configuring the SDK with `setCrashReportingState(Feature.State.DISABLED)`. This was overriding our expected error handling and masking further crashes. Is this issue also resolved in the snapshot?

**Comment by Korazy** [comment]
Hey @jdamcd 

Would you be able to explain the issue further?

**Comment by linean** [comment]
@jdamcd this is exact same thing that I've described :)

**Comment by jdamcd** [comment]
Sure. We've observed an issue with `Thread.setDefaultUncaughtExceptionHandler()` being set in addition to `RxJavaPlugins.setErrorHandler()` which @linean described. It's unexpected because we're not using Instabug for crash reporting.

**Comment by ramiimagdi** [comment]
Hey all, 

Apologies for taking some time on this, I just want to let you know that the issue is still being investigated, and we'll be reaching out to you as soon as we get a hand on it.

Thank you for your patience.

**Comment by linean** [comment]
What about if someone is using custom exceptions handler, will Instabug overrides it silently? And sorry for asking, but I'm lost, what is the status of this issue?

**Comment by jdamcd** [comment]
@Korazy Here's a sample project to demonstrate that initialising the Instabug SDK alters RxJava behaviour: https://github.com/jdamcd/instabug-rx-issue

**Comment by Korazy** [comment]
Out of curiousity, did the snapshot I sent before not fix the issue for you?

**Comment by jdamcd** [comment]
> Out of curiousity, did the snapshot I sent before not fix the issue for you?

It fixes the core issue since no `RxJavaPlugins` error handler is set. However, the SDK then crashes internally from system `onLowMemory()` callbacks. Reproduction steps in the sample project: https://github.com/jdamcd/instabug-rx-issue/pull/1

**Comment by linean** [comment]
@Korazy 8.0.11.4-SNAPSHOT works for me :)

**Comment by Korazy** [comment]
@linean awesome!

@jdamcd we’ll look into that right away.

**Comment by Korazy** [comment]
@jdamcd would you be able to try this snapshot? `8.0.11.19-SNAPSHOT`

**Comment by jdamcd** [comment]
@Korazy `8.0.11.19-SNAPSHOT` resolves both issues. Thanks for your help! 🎉

**Comment by Korazy** [comment]
Awesome! Glad everything is working out now 😄

**Comment by Karambar** [comment]
Hi @Korazy ,

I encounter the same issue, could we have an update ?
Will it be available soon on the stable build ?
I added a fix on my side but I should not have to do this hack.

Thanks for your help !

**Comment by jdamcd** [comment]
Any news on when this fix will be included in a stable release @Korazy?

**Comment by Axrorxoja** [comment]
I have same issue in in 8.1.2 version 
`java.lang.NoSuchMethodError: No virtual method setHeaders(Ljava/lang/String;)V in class Lcom/instabug/library/model/NetworkLog; or its super classes (declaration of 'com.instabug.library.model.NetworkLog' appears in /data/app/com.mysuperdispatch.android-XXXJAfLGgWcyo1G0xvz6vg==/split_lib_slice_0_apk.apk!classes2.dex)
        at com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.intercept(InstabugOkhttpInterceptor.java:128)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`

**Comment by mzelzoghbi** [comment]
Hi @Axrorxoja , Thanks for reporting this. We think that this issue is not related to the one mentioned in the thread from the beginning. Can you double check it? Also, You should be sure that you are using the latest version of `instabug-with-okhttp-interceptor`  which is **8.1.2**.

**Comment by Axrorxoja** [comment]
Hi @mzelzoghbi thank you for feedback

**Comment by mzelzoghbi** [comment]
Awesome! Glad everything is working out now 😄
