### ISSUE TITLE
Crash:IllegalStateException

### ISSUE THREAD

**Issue by chenliuyun** [Instabug/Instabug-Android#184]
### Steps to Reproduce the Problem
show screen Instagbug and submit issues
### Actual Behavior
some user crashed
### Instabug integration code

new Instabug.Builder(this, BuildConfig.DEBUG ? "xx" : "xx")
.setInvocationEvents(InstabugInvocationEvent.NONE)
.build();
Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeLight);
Instabug.setWelcomeMessageState(WelcomeMessage.State.DISABLED);
BugReporting.setPromptOptionsEnabled(PromptOption.BUG, PromptOption.FEEDBACK);
and log:
InstabugLog.i(msg);

### SDK Version
8.2.0
### Android Version
 minSdkVersion 18
 compileSdkVersion 28
 buildToolsVersion '28.0.3'
 targetSdkVersion 28
### Device Model
 austin, Android 5.1
Motorola Nexus 6 (shamu), Android 7.1,
Sony Xperia Z5 Compact (SO-02H), Android 7.0

### [Optional] Project That Reproduces the Issue
java.lang.IllegalStateException: 
  at com.instabug.library.internal.storage.cache.db.DatabaseManager.getInstance (DatabaseManager.java:24)
  at com.instabug.library.logging.a.b (InstabugLogDbHelper.java:84)
  at com.instabug.library.logging.a.a (InstabugLogDbHelper.java:32)
  at com.instabug.library.logging.a$1.a (InstabugLogDbHelper.java:58)
  at com.instabug.library.logging.a$1.onNext (InstabugLogDbHelper.java:43)
  at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal (ObservableObserveOn.java:201)
  at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run (ObservableObserveOn.java:255)
  at io.reactivex.internal.schedulers.ScheduledRunnable.run (ScheduledRunnable.java:66)
  at io.reactivex.internal.schedulers.ScheduledRunnable.call (ScheduledRunnable.java:57)
  at java.util.concurrent.FutureTask.run (FutureTask.java:237)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:272)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:761)

**Comment by theywrong** [comment]
Help my whole device is controled

**Comment by chenliuyun** [comment]
Hello,any update?

**Comment by mzelzoghbi** [comment]
Hi @chenliuyun , Thanks for reporting this, We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if the snapshot fixed the issue for you?

```
implementation 'com.instabug.library:instabug:8.2.0.5-SNAPSHOT'
```
you will need to add these lines to your app `build.gradle` before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

This **SNAPSHOT** is completely safe to use and has no debug code at all.

**Comment by chenliuyun** [comment]
Hi, @mzelzoghbi ,I am sorry  forget to mention that we have tried the version(8.2.0.5-SNAPSHOT) after checked [issue181](https://github.com/Instabug/Instabug-Android/issues/181) .But the problem is still there.

**Comment by mzelzoghbi** [comment]
@chenliuyun Can you reproduce it on a sample project ?

**Comment by theywrong** [comment]
I'm going to send my bug report

**Comment by theywrong** [comment]
OK,???

**Comment by mzelzoghbi** [comment]
Hey @theywrong 
Would you be able to reach out to our support team using contactus@instabug.com so that we can further investigate this issue?

**Comment by theywrong** [comment]
Ok

On Apr 21, 2019 6:37 AM, "Mohamed Zakaria El-Zoghbi" <
notifications@github.com> wrote:

Hey @theywrong <https://github.com/theywrong>
Would you be able to reach out to our support team using
contactus@instabug.com so that we can further investigate this issue?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Instabug/Instabug-Android/issues/184#issuecomment-485241646>,
or mute the thread
