### ISSUE TITLE
Screen record crash on Android 10

### ISSUE THREAD

**Issue by Pirksy** [Instabug/Instabug-Android#245]
`
java.lang.RuntimeException: Unable to start service com.instabug.library.internal.video.ScreenRecordingService@94e4d7e with Intent { cmp=....stage/com.instabug.library.internal.video.ScreenRecordingService (has extras) }: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
        at android.app.ActivityThread.access$1800(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION 
`

**Comment by yongjhih** [comment]
It works well after downgraded the android target SDK to 28.

> Make sure you call startForeground() before getMediaProjection()!
> 
> The best solution is to call startForeground() from onCreate() without any conditions, displaying some sort of default messages in notification. Then you can execute your logic and call NotificationManager.notify() with updated notification at any time.

ref. https://stackoverflow.com/a/57186064/2872224

> Foreground service permission | Apps wanting to use foreground services must now request the FOREGROUND_SERVICE permission first. This is a normal permission, so the system automatically grants it to the requesting app. Starting a foreground service without the permission throws a SecurityException.

ref. https://developer.android.com/about/versions/pie/android-9.0-migration#tya

**Comment by mzelzoghbi** [comment]
Hello @Pirksy @yongjhih  Thanks for reporting this.
We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
```
implementation 'com.instabug.library:instabug:9.0.3.8-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You

**Comment by Pirksy** [comment]
Hello @mzelzoghbi ! Snapshot version crashes app after recording with 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx.xxx.stage, PID: 5684
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by mzelzoghbi** [comment]
@Pirksy Yes you are totally right, there was an issue on 8.x.x I updated the snapshot can you try it again after running this command `./gradlew build --refresh-dependencies`

Thank You

**Comment by Pirksy** [comment]
Yeap, it works :) Thanks!

**Comment by eygraber** [comment]
This is still broken on 9.0.4

Android 10 has been out for almost a year now if you include the betas, and almost 6 months of having a stable API. How does a service that charges users not fix bugs of this magnitude. It's like I'm paying you to crash my user's devices.

**Comment by mzelzoghbi** [comment]
Hello Eliezer,

We appreciate your feedback a lot, your words definitely make a lot of sense on our side! That's not definitely our intentions, I mean we wouldn't love that to happen to our users as well. We created a snapshot fix for you to resolve this issue, you can find it here **9.0.4.2-SNAPSHOT**. Please give it a try, also, it'll be fully released to our next version coming up very soon.
We apologize again for any delays and please let us know if you have any other questions.

**Comment by CrisBarreiro** [comment]
As v9.0.5 was already released, shouldn't this issue be closed?

**Comment by mzelzoghbi** [comment]
@CrisBarreiro You are right 👍 

Thank You 😄

**Comment by mishaMikhail** [comment]
@mzelzoghbi, unfortunately I am able to reproduce this bug in the Xamarin.Android project. On Google Pixel (API 29).  instabug-for-android version 9.0.5
**Stack trace:**
  ```
--- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Unable to start service com.instabug.library.internal.video.ScreenRecordingService@5176fca with Intent { cmp=com.project/com.instabug.library.internal.video.ScreenRecordingService (has extras) }: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4105)
	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
	at android.media.projection.MediaProjection.<init>(MediaProjection.java:58)
	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:104)
	at com.instabug.library.internal.video.a.<init>(ScreenRecordingSession.java:16)
	at com.instabug.library.internal.video.ScreenRecordingService.onStartCommand(ScreenRecordingService.java:21)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:476)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by AliAbdelfattah** [comment]
@mishaMikhail please follow up with us on this issue instead https://github.com/Instabug/Instabug-Android/issues/273#issuecomment-581503249

**Comment by MilotH2** [comment]
issue still exists, on targetSdkVersion 29, i added 28 and issue is gone.
