### ISSUE TITLE
NPE in InstabugOkhttpInterceptor

### ISSUE THREAD

**Issue by edenman** [Instabug/Instabug-Android#259]
### Steps to Reproduce the Problem
Add the instabug http interceptor

### Expected Behavior
Log http calls to instabug
 
### Actual Behavior
Crash

### Instabug integration code
In Application subclass, called at the end of onCreate:
```
    Instabug.Builder(this, instabugToken)
      .setConsoleLogState(Feature.State.ENABLED)
      .setInvocationEvents(InstabugInvocationEvent.SHAKE)
      .setUserDataState(Feature.State.DISABLED)
      .build()
    Instabug.setColorTheme(InstabugColorTheme.InstabugColorThemeLight)
    Instabug.setDebugEnabled(BuildConfig.DEBUG)
```

In Dagger module that sets up networking:
```
    val builder = OkHttpClient.Builder()
      .cache(cache)
      .connectTimeout(TIMEOUT_PERIOD, TimeUnit.MINUTES)
      .readTimeout(TIMEOUT_PERIOD, TimeUnit.MINUTES)
      .addNetworkInterceptor(loggingInterceptor)
      .addInterceptor(authInterceptor)
      .addInterceptor(InstabugOkhttpInterceptor())
      .build()
```

### SDK Version
9.0.3

### Android Version
23

### Device Model
emulator

### Stacktrace
```
12-10 12:42:25.780 E/AndroidRuntime( 4981): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.MediaType.toString()' on a null object reference
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.populateNetworkResponse(InstabugOkhttpInterceptor.java:212)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.intercept(InstabugOkhttpInterceptor.java:88)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at com.envoy.app.api.AuthInterceptor.intercept(AuthInterceptor.kt:16)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-10 12:42:25.780 E/AndroidRuntime( 4981): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by mzelzoghbi** [comment]
Hi @edenman, .
Thanks for reporting this We created a **SNAPSHOT** that should fix the issue, Can you please try it and tell us if the snapshot fixed the issue for you?
```
implementation 'com.instabug.library:instabug:9.0.3.11-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You

**Comment by edenman** [comment]
Snapshot does indeed fix the NPE issue.  Now I've got a different exception in my code:
```
         AndroidRuntime  E  FATAL EXCEPTION: main
                         E  Process: com.envoy.app, PID: 11639
                         E  com.apollographql.apollo.exception.ApolloParseException: Failed to parse http response
                         E      at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:101)
                         E      at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
                         E      at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$2.onResponse(ApolloServerInterceptor.java:144)
                         E      at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                         E      at java.lang.Thread.run(Thread.java:818)
                         E  Caused by: java.io.EOFException: End of input
                         E      at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.nextNonWhitespace(BufferedSourceJsonReader.java:946)
                         E      at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.doPeek(BufferedSourceJsonReader.java:332)
                         E      at com.apollographql.apollo.internal.json.BufferedSourceJsonReader.beginObject(BufferedSourceJsonReader.java:169)
                         E      at com.apollographql.apollo.response.OperationResponseParser.parse(OperationResponseParser.java:82)
                         E      at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:87)
                         E      ... 6 more
```

I'm guessing your interceptor is consuming the response body so the stream is empty when my actual response processor gets it?  I could be wrong, but if you look at OkHttp's `HttpLoggingInterceptor` it does some `clone` operations on the buffer, presumably so it doesn't consume the original response buffer?

**Comment by mzelzoghbi** [comment]
@edenman This shouldn't happen, we only copy the response and pass it to the next layer. Can you send us the debug logs ? You will need to enable it by using `Instabug.setDebugEnabled(true);` 

Thank You

**Comment by edenman** [comment]
Here ya go:
```
12-11 09:39:52.974 D/IB-InstabugInternalTrackingDelegate(14897): OnboardingActivity created
12-11 09:39:52.979 D/IB-InstabugInternalTrackingDelegate(14897): OnboardingActivity started
12-11 09:39:52.993 D/IB-InstabugInternalTrackingDelegate(14897): OnboardingActivity resumed
12-11 09:39:52.993 V/IB-PresentationManager(14897): !InstabugCore.isForegroundBusy(): true
12-11 09:39:58.617 V/IB-InstabugOkhttpInterceptor(14897): populate network request started
12-11 09:39:59.188 V/IB-InstabugOkhttpInterceptor(14897): plain text buffer
12-11 09:39:59.189 V/IB-InstabugOkhttpInterceptor(14897): inserting network log
12-11 09:39:59.189 D/IB-InstabugNetworkLogDbHelper(14897): insert
12-11 09:40:02.052 V/IB-InstabugOkhttpInterceptor(14897): populate network request started
12-11 09:40:02.052 V/IB-InstabugOkhttpInterceptor(14897): plain text buffer
12-11 09:40:02.455 V/IB-InstabugOkhttpInterceptor(14897): plain text buffer
12-11 09:40:02.455 V/IB-InstabugOkhttpInterceptor(14897): inserting network log
12-11 09:40:02.455 D/IB-InstabugNetworkLogDbHelper(14897): insert
12-11 09:40:02.517 V/IB-InstabugOkhttpInterceptor(14897): populate network request started
12-11 09:40:02.517 V/IB-InstabugOkhttpInterceptor(14897): plain text buffer
12-11 09:40:05.685 V/IB-InstabugOkhttpInterceptor(14897): plain text buffer
12-11 09:40:05.686 V/IB-InstabugOkhttpInterceptor(14897): inserting network log
12-11 09:40:05.686 D/IB-InstabugNetworkLogDbHelper(14897): insert
12-11 09:40:05.744 D/IB-InstabugFeaturesManager(14897): start saving app_features
12-11 09:40:05.744 D/IB-InstabugFeaturesManager(14897): finish saving app_features
12-11 09:40:05.762 D/IB-InstabugDelegate(14897): Dumping caches
12-11 09:40:05.769 D/IB-InstabugFeaturesManager(14897): Last fetched at is more than 0 millis, retrieve it again
12-11 09:40:25.775 W/ActivityManager( 1649): Timeout executing service: ServiceRecord{abfde9f u0 com.envoy.app/com.instabug.library.network.worker.uploader.InstabugSessionUploaderService}
12-11 09:40:25.785 I/ActivityManager( 1649): Crashing app skipping ANR: ProcessRecord{ba61158 14897:com.envoy.app/u0a61} executing service com.envoy.app/com.instabug.library.network.worker.uploader.InstabugSessionUploaderService
12-11 09:40:55.092 W/ActivityManager( 1649): Scheduling restart of crashed service com.envoy.app/com.instabug.library.analytics.network.InstabugAnalyticsUploaderService in 98534ms
12-11 09:40:55.092 W/ActivityManager( 1649): Scheduling restart of crashed service com.envoy.app/com.instabug.library.network.worker.uploader.InstabugSessionUploaderService in 108533ms
12-11 09:40:56.297 W/System.err(15035): 	at com.instabug.library.b.<init>(InstabugDelegate.java:16)
12-11 09:40:56.297 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:6)
12-11 09:40:56.297 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:57)
12-11 09:40:56.297 W/System.err(15035): 	at com.envoy.app.EnvoyApplication.initInstabug(EnvoyApplication.kt:66)
12-11 09:40:56.299 W/System.err(15035): 	at com.instabug.library.b.<init>(InstabugDelegate.java:16)
12-11 09:40:56.299 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:6)
12-11 09:40:56.299 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:57)
12-11 09:40:56.299 W/System.err(15035): 	at com.envoy.app.EnvoyApplication.initInstabug(EnvoyApplication.kt:66)
12-11 09:40:56.302 W/System.err(15035): 	at com.instabug.library.b.<init>(InstabugDelegate.java:16)
12-11 09:40:56.302 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:6)
12-11 09:40:56.302 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:57)
12-11 09:40:56.302 W/System.err(15035): 	at com.envoy.app.EnvoyApplication.initInstabug(EnvoyApplication.kt:66)
12-11 09:40:56.303 W/System.err(15035): 	at com.instabug.library.b.<init>(InstabugDelegate.java:16)
12-11 09:40:56.303 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:6)
12-11 09:40:56.303 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:57)
12-11 09:40:56.303 W/System.err(15035): 	at com.envoy.app.EnvoyApplication.initInstabug(EnvoyApplication.kt:66)
12-11 09:40:56.304 W/System.err(15035): 	at com.instabug.library.b.<init>(InstabugDelegate.java:16)
12-11 09:40:56.304 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:6)
12-11 09:40:56.304 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:57)
12-11 09:40:56.304 W/System.err(15035): 	at com.envoy.app.EnvoyApplication.initInstabug(EnvoyApplication.kt:66)
12-11 09:40:56.334 W/System.err(15035): 	at com.instabug.library.m.a.a(InstabugSurvey.java:13)
12-11 09:40:56.334 W/System.err(15035): 	at com.instabug.library.m.a.a(InstabugSurvey.java:1)
12-11 09:40:56.334 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:47)
12-11 09:40:56.334 W/System.err(15035): 	at com.instabug.library.Instabug$Builder.build(Instabug.java:57)
12-11 09:40:56.334 W/System.err(15035): 	at com.envoy.app.EnvoyApplication.initInstabug(EnvoyApplication.kt:66)
12-11 09:40:56.336 I/IB-Instabug(15035): setDebugEnabled true
12-11 09:40:56.364 V/IB-InstabugAnalyticsUploaderService(15035): New InstabugAnalyticsUploaderService created
12-11 09:40:56.367 V/IB-InstabugAnalyticsUploaderService(15035): InstabugAnalyticsUploaderService started with intent Intent { cmp=com.envoy.app/com.instabug.library.analytics.network.InstabugAnalyticsUploaderService }
12-11 09:40:56.369 V/IB-InstabugSessionUploaderService(15035): New InstabugSessionUploaderService created
12-11 09:40:56.372 V/IB-InstabugSessionUploaderService(15035): InstabugSessionUploaderService started with intent Intent { cmp=com.envoy.app/com.instabug.library.network.worker.uploader.InstabugSessionUploaderService }
12-11 09:40:56.419 V/IB-InstabugAnalyticsUploaderService(15035): Internet is good to go
12-11 09:40:56.419 V/IB-InstabugAnalyticsUploaderService(15035): Starting InstabugAnalyticsUploaderService task
12-11 09:40:56.433 V/IB-InstabugSessionUploaderService(15035): Internet is good to go
12-11 09:40:56.433 V/IB-InstabugSessionUploaderService(15035): Starting InstabugSessionUploaderService task
12-11 09:40:56.441 D/IB-InstabugSessionUploaderService(15035): Found 1 sessions in cache
12-11 09:40:56.466 V/IB-InstabugAnalyticsUploaderService(15035): InstabugAnalyticsUploaderService destroyed
12-11 09:40:56.909 D/IB-InstabugSessionUploaderService(15035): Session id: -1, startedAt: 1576085985, duration: 20 synced successfully
12-11 09:40:56.917 D/IB-InstabugSessionUploaderService(15035): Session deleted: id: -1, startedAt: 1576085985, duration: 20
12-11 09:40:56.919 V/IB-InstabugSessionUploaderService(15035): InstabugSessionUploaderService destroyed
```

**Comment by edenman** [comment]
(logcat grepped for Instabug with the `setDebugEnabled(true)` call)

**Comment by mzelzoghbi** [comment]
@edenman I can't see any errors in the logs. 
Can you put a breakpoint in our interceptor and see what is happening to the response body?

**Comment by edenman** [comment]
before your interceptor reads the response:
<img width="861" alt="Screen Shot 2019-12-16 at 3 42 02 PM" src="https://user-images.githubusercontent.com/1063557/70952292-a8b69d00-201a-11ea-826d-72f3bbf0a59e.png">
after your interceptor runs, the `ApolloInterceptor` tries to parse the response, but you've consumed the response body so it can't be read:
<img width="875" alt="Screen Shot 2019-12-16 at 3 42 56 PM" src="https://user-images.githubusercontent.com/1063557/70952319-bff58a80-201a-11ea-9d01-833feebcfad1.png">

**Comment by mzelzoghbi** [comment]
@edenman I checked our codebase and debugged it I didn't find anything seems there is a problem with the parse probably it is an issue with **apollograph** client.

The good thing is that our Interceptor is not Proguarded so you can simply check the entire code and copy it to a new interceptor and try playing with it if you still think there is something wrong in it.

And let us know if you have any thoughts or need further help.

Thank You

**Comment by samrombswm** [comment]
Hello I am still getting the original error on SDK version 9.0.4

**Comment by marcorighini** [comment]
Same happens to us, and we are not using apollograph.
@mzelzoghbi I think should be reopened

**Comment by mzelzoghbi** [comment]
@marcorighini I think you are talking about another issue, can you share with us the stacktrace ?

**Comment by edenman** [comment]
FWIW I ended up just writing this simple interceptor because I couldn't get the Instabug one to work:

```
class OkHttpTimingInterceptor : Interceptor {
  override fun intercept(chain: Interceptor.Chain): Response {
    val start = DebugTimer.start({ str -> InstabugLog.d(str) })
    val request = chain.request()
    try {
      return chain.proceed(request)
    } finally {
      val graphQLOperationName = request.header("X-APOLLO-OPERATION-NAME")
      if (graphQLOperationName.isNullOrBlank()) {
        start.log("REST request ${request.url}")
      } else {
        start.log("GraphQL request $graphQLOperationName")
      }
    }
  }
}
```

**Comment by MichaelDark** [comment]
Hi @mzelzoghbi 

We still are facing this issue and I think I might help.

Actually, I think I know from where this NPE could come.
Have a look at this part of code.

```
InstabugOkhttpInterceptor.java (Decompiled)
209: MediaType contentType = responseBody.contentType();
210:                 if (contentType != null) {
211:                     if (contentType.toString().equals("application/protobuf")) {
```

Here we have a crash on line:211. I think it is because `contentType.toString()` under the hood may return `null`, while `"application/protobuf"` is a constant `String`, which we can compare with `.equals(...)`, even to `null` objects since the result of `equals` will anyway be `false` in this case.

And this file `InstabugOkhttpInterceptor.java` is full of such some kind of mistakes, where instead of comparing _constant_ to some  _possible nullable getted value_ we compare some _possible nullable string_ to the _constant_ , and I think it is the key to this issue.

Please, send or show this to someone from Instabug Core team, I am looking forward to have a fix of this NPE as soon as possible

**Comment by mzelzoghbi** [comment]
@MichaelDark can you please try this **SNAPSHOT** it should fix the issue.
```
implementation 'com.instabug.library:instabug:9.0.5.2-SNAPSHOT'
```
you will need to add these lines to your app **build.gradle** before your dependencies
```
repositories {
    ....
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```
This **SNAPSHOT** is completely safe to use and has no debug code at all.

Thank You 😊

**Comment by MichaelDark** [comment]
@mzelzoghbi but the file I have mentioned [here](https://github.com/Instabug/Instabug-Android/issues/259#issuecomment-583626275) is from `com.instabug.library:instabug-with-okhttp-interceptor:9.0.5'` dependency, how it could be fixed if straight-forward solution should be done in a class from this dependency?

This bug is unpredictable and it is very hard to reproduce it, but it has high regression. You can still make fix in a SNAPSHOT for `com.instabug.library:instabug-with-okhttp-interceptor:9.0.5'`, and then just mention it here for us to check it.

**Comment by mzelzoghbi** [comment]
@MichaelDark Sorry my bad, I updated the comment 🙏

**Comment by MichaelDark** [comment]
@mzelzoghbi Still no changes in lines that I've mentioned [here](https://github.com/Instabug/Instabug-Android/issues/259#issuecomment-583626275) (this comment is about `implementation 'com.instabug.library:instabug-with-okhttp-interceptor:9.0.5.2-SNAPSHOT'`)

**Comment by MichaelDark** [comment]
@mzelzoghbi Please, re-open this issue.  
Because we still have no solution for this issue and we are still facing it.  
Very disappointing that _tool for crash reporting produces crashes_.

Still waiting for [described](https://github.com/Instabug/Instabug-Android/issues/259#issuecomment-583626275) fix.

**Comment by mzelzoghbi** [comment]
Hi @MichaelDark  ,
Please accept our apologies for the inconveniences we may have caused. I completely understand how that can be frustrating. Please rest assured that we’re always working on improving the stability of our SDKs while introducing new helpful features.

We check the snapshot `9.0.5.2` and we are sure that the fix should be included in it (attached screenshot from decompiled.java file) However, we created another snapshot with the same fix `9.0.5.5-SNAPSHOT` please try any of them again and make sure you run `./gradlew build --refresh-dependencies` to update any cached dependencies as it may be a caching issue.


![Screen Shot 2020-02-10 at 10 37 46 AM](https://user-images.githubusercontent.com/5540492/74133514-66ac7080-4bf1-11ea-9472-a680819c4796.png)


I'll reopen this again till you confirm that the fix worked for you.

**Comment by MichaelDark** [comment]
@mzelzoghbi Still not fixed. Check screenshots of `9.0.5.5-SNAPSHOT` (_especially lines_)

Your fix:
![image](https://user-images.githubusercontent.com/28561249/74135064-4c27c680-4bf4-11ea-87fb-8d1b3152714c.png)

Needed fix:
![image](https://user-images.githubusercontent.com/28561249/74135155-75e0ed80-4bf4-11ea-9dac-f72ff45cc41b.png)

**Comment by MichaelDark** [comment]
@mzelzoghbi 

Maybe, it will be a good idea to annotate it with `@NonNull`
![image](https://user-images.githubusercontent.com/28561249/74135278-b3457b00-4bf4-11ea-9248-3fdae52c2307.png)

**Comment by mzelzoghbi** [comment]
For the 1st screenshot you are totally right, can you try `9.0.5.6-SNAPSHOT` and let us know? 
For the 2nd screenshot, we already compile okhttp3 official library in our interceptor so we can't change its implementation.

**Comment by MichaelDark** [comment]
@mzelzoghbi Thank you, I've checked - fix is here. We will check this snapshot and provide you feedback as soon as possible 😉

**Comment by mzelzoghbi** [comment]
@MichaelDark Happy to hear that everything worked now, I'll leave this open till the fix is included in our release. I'll make sure to include it in our next official release planned to be within 2 weeks.

Please feel free to reach out to us again if you encountered any issues.

Have a nice day.

**Comment by MichaelDark** [comment]
@mzelzoghbi Seems like this bug is fixed in `9.0.5.6-SNAPSHOT`. 
Looking forward to see this fix in next release.

P.S. I would be great if someone could walk through the whole interceptor and fix all possible cases for NPE, because there are enough of them

**Comment by mzelzoghbi** [comment]
Hello Everyone, This issue has been fixed on **9.1.0**.
Please feel free to reach out to us again if you encountered any issues.

Thank You
