### ISSUE TITLE
InstabugUserEventLogger spawns a new thread for every event and never releases it

### ISSUE THREAD

**Issue by AndrewMorsillo** [Instabug/Instabug-Android#333]
My react-native app on Android slows down over time. Even on flagship devices it eventually slows to a crawl and becomes unusable. I suspect that Instabug is the culprit due to not releasing resources it acquires. It spawns a new thread on every event logged and never seems to reuse or discard them. I'm not very familiar with native Android development so I don't know if this behavior is expected but it certainly seems suspicious.

![image](https://user-images.githubusercontent.com/858965/92768187-c88aaf80-f365-11ea-897e-540a091e3078.png)

### Steps to Reproduce the Problem
Run android profiler again an instabug-reactnative project

### Expected Behavior
Instabug releases any resources it acquires

### Actual Behavior
InstabugUserEventLogger spawns a thread such as `pool-264-thread-1` for every single event logged, the list of threads in the profiler becomes extremely long

### SDK Version
instabug-reactnative "https://github.com/Instabug/Instabug-React-Native/#custom/INSD-4430/fix-oom-v9.1.6"

### Android Version
Any

### Device Model
Any

**Comment by AndrewMorsillo** [comment]
I've confirmed this stops if I remove instabug from the app. Without instabug the number of threads remains stable. With Instabug the number of threads grows with every event and is unbounded.

**Comment by MahmoudAmin39** [comment]
Hi @AndrewMorsillo,
Thanks for reporting this issue. Please accept our apologies that you faced it.
We are working on a fix and We will get back to you with it ASAP.
Thanks for understanding. 🙏

**Comment by MahmoudAmin39** [comment]
Hi @AndrewMorsillo ,
We created a **BUILD** that should fix the issue, Can you please try it and tell us if it fixed the issue for you?
```
npm install --save https://github.com/Instabug/Instabug-React-Native\#snapshot-android/9.1.7.1-INSD-4445
```
This **BUILD** is completely safe to use and has no debug code at all.
Thank You :smiley:

**Comment by AndrewMorsillo** [comment]
@MahmoudAmin39 Something seems _very_ wrong with this build. I can't even take a trace with the Android Studio profiler to check the thread issue. When I try, RxComputationThread appears to be locked up with 100% CPU slowing the app to a crawl and eventually causing a crash.

**Comment by AndrewMorsillo** [comment]
Right now it only seems to lock up if the Android Studio profiler is connected but there may be other issue. I encountered some strange behavior with Firebase Firestore in my signup flow that I'd never seen before. Is Instabug somehow interfering with network requests? 



There are actually several threads related to instabug that appear to be locking up the app

![image](https://user-images.githubusercontent.com/858965/93391963-ff693580-f83d-11ea-9f32-2c02640f8279.png)

This one appears to be formatting dates?
![image](https://user-images.githubusercontent.com/858965/93392056-24f63f00-f83e-11ea-855e-3c4adf3f7958.png)

**Comment by AndrewMorsillo** [comment]
This build also does not appear to resolve this issue https://github.com/Instabug/Instabug-React-Native/issues/505

I still see `Invalid ID 0x0000.....` logged on every tap.

**Comment by TMcLoone** [comment]
Any update on this?

**Comment by mzelzoghbi** [comment]
@TMcLoone This has been released. Please upgrade to our latest release `10.1.1` and let us know if you faced any further issues. 🙏🏻
